[package]
name = "ramaria-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ramaria"
path = "src/main.rs"

[dependencies]
ramaria-app = { path = "../ramaria-app" }
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
windows.workspace = true
